defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: wago_development

test:
  <<: *defaults
  database: wago_test

cucumber:
  host: <%= ENV['MONGOID_HOST'] || 'localhost' %>
  database: wago_cucumber  

# set these environment variables on your prod server
production:
  <<: *defaults
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>